# fly.toml app configuration file generated for coco-backend on 2025-10-28T17:23:53-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coco-backend'
primary_region = 'sjc'

[build]

[deploy]
  release_command = 'alembic upgrade head'

[env]
  APP_ENV = 'production'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 200
    soft_limit = 180

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/healthz'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
